import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime
import os
from dotenv import load_dotenv

load_dotenv()

def send_weekly_report(stats_data):
    recipients = ["gads.advertisement@gmail.com", "baagish@gmail.com"]
    sender_email = os.environ.get("SMTP_USER", "advit@iadsclick.com")
    smtp_pass = os.environ.get("SMTP_PASS", "your_app_password")
    
    msg = MIMEMultipart('alternative')
    msg['Subject'] = f"📊 iAdsClick Weekly Lead Intelligence: {datetime.now().strftime('%b %d')}"
    msg['From'] = sender_email
    msg['To'] = ", ".join(recipients)

    html = f"""
    <html>
      <body style="font-family: Arial, sans-serif; color: #333;">
        <h2 style="color: #2e7d32;">iAdsClick Performance Summary</h2>
        <p>Your AI Agent discovered <b>{stats_data.get('new_niches', 0)} new niches</b> this week.</p>
        
        <table border="1" cellpadding="10" style="border-collapse: collapse; width: 100%;">
          <tr style="background-color: #f2f2f2;">
            <th>Niche</th>
            <th>Clicks (WA)</th>
            <th>Top Lead</th>
          </tr>
          {stats_data.get('table_rows', '')}
        </table>
        
        <p><i>Next Steps: {stats_data.get('recommendation', 'Keep tracking go.php clicks.')}</i></p>
        <hr>
        <p style="font-size: 10px;">Generated by NexusHunt AI - {datetime.now()}</p>
      </body>
    </html>
    """
    
    msg.attach(MIMEText(html, 'html'))
    
    try:
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(sender_email, smtp_pass)
            server.sendmail(sender_email, recipients, msg.as_string())
        print("🚀 Weekly Report Dispatched.")
    except Exception as e:
        print(f"Failed to send email. Check SMTP_USER and SMTP_PASS in your .env.\nError: {e}")

if __name__ == "__main__":
    print("Preparing Weekly Analytics Report...")
    dummy_stats = {
        "new_niches": 2,
        "table_rows": "<tr><td>parents</td><td>45</td><td>John Doe</td></tr><tr><td>re_noida</td><td>12</td><td>Apex Real Estate</td></tr>",
        "recommendation": "High engagement in 'parents' niche. Consider creating more targeted campaigns."
    }
    send_weekly_report(dummy_stats)
